### ISSUE TITLE
There have been new code integration in recent months. Is there any plan to release a new version?

### ISSUE THREAD

**Issue by chemsky** [Tessil/array-hash#11]
There have been new code integration in recent months. Is there any plan to release a new version?

@Tessil

**Comment by Tessil** [comment]
Hi,

I can eventually create a release but there is nothing that has really changed functionally (nor any bug corrected). The changes are mainly some formatting, CI update and changed the way Boost.Test was linked for the tests.

Any reason you need a new version tag?

**Comment by chemsky** [comment]
It's only been a long time since the last version was released. I want to confirm whether there is a new version released recently. thank you.

**Comment by Tessil** [comment]
Thanks, I'll close this issue then. I'll make sure to create a release when a bug is corrected or feature added, a new release now seems superfluous.
