### ISSUE TITLE
array_set::deserialize() creates an undesired new array_set(0)

### ISSUE THREAD

**Issue by krfall** [Tessil/array-hash#6]
I have been experimenting with the new (de)serialization code for this container.  Thanks for putting it in.  (actually I have been using Boost to serialize it, which could be smoother, but nonetheless).

I have a class that defines one of these and I do not wish deserialize() to return a new/different one.
At the moment the code is as follows:

    template<class Deserializer>
    static array_set deserialize(Deserializer& deserializer, bool hash_compatible = false) {
        array_set set(0);
        set.m_ht.deserialize(deserializer, hash_compatible);

        return set;
    }

I added the following which seems to work for my purposes (and changed the currently existing static version to be called static_deserialize()):

    void deserialize(Deserializer& deserializer, bool hash_compatible = false) {
        assert(m_ht.size() == 0);
        m_ht.deserialize(deserializer, hash_compatible);
        return;
    }

There may be different/better ways to achieve this result (?), but I would be pleased if there was at least some way to avoid the static allocation currently there.  Regards... -k

**Comment by Tessil** [comment]
Hi,

I went with the static method to be sure that the `array_map` is empty and has a bucket count of 0, these are the preconditions in the private `deserialize` method of `array_hash` (the requirement on bucket count could be easily removed). I could effectively have a non-static method that throws an exception if it isn't the case.

But why do you need a non-static method? The creation of the empty `array_map` has a really really minor cost (no heap allocation) and if you have to set an already existing `array_map` the newly deserialized map would be moved into it (which is also a really minor cost compared to the whole deserialization process).

I can see one advantage, if there is already enough buckets in the existing map, we could avoid one allocation for the bucket array (but we may use more memory than necessary if there is more buckets than required).
